services:
  postgres-postgresql:
    image: postgres:11.3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crmv  
    ports:
      - 5432:5432
      
